### ISSUE TITLE
Completing scenario 33 doesn't block scenario 34

### ISSUE THREAD

**Issue by solbero** [dmungin/gloomhaven-scenario-tree-ng#6]
When a party completes scenario 33 "Savaas Armory" they should have both the "Drake's Command" and tthe "Drake's Treasure" party achievements. This would give the party the global achievement "The Drake Aided" which blocks scenario 34 "Scorched Summit".

This blocking is not reflected in Scenario Tree Viewer.

**Comment by dmungin** [comment]
I'll look into a way of correctly reflecting these in the tree logic. Thanks.

**Comment by shawndibble** [comment]
Note that this is only true in a single party campaign. In a multiple party campaign, You can have one party do 33 with voice's command and another do 25 for drake's command. Thus stopping the global achievement and allowing 34 to be reachable.

But it is true in a single party campaign that if 25 is complete, 33 would block 34.

**Comment by dmungin** [comment]
I implemented the blocking logic with the assumption of a single party campaign. Since there isn't any support for multi-party campaigns elsewhere in the app I'm ok with this solution for now. If it causes issues for some people there is nothing stopping them from overriding this logic if they see fit.
